export const publicationTypes = [
    { key: "allTypes", label: "All types" },
    { key: "journalArticles", label: "Journal Articles" },
    { key: "bachelorTheses", label: "Bachelor Theses" },
    { key: "books", label: "Books" },
    { key: "conferences", label: "Conferences" },
    { key: "bookChapters", label: "Book Chapters" },
    { key: "proceedingsArticles", label: "Proceedings Articles" },
    { key: "mastersTheses", label: "Masters Theses" },
    { key: "miscellaneous", label: "Miscellaneous" },
    { key: "patents", label: "Patents" },
    { key: "phdTheses", label: "PhD Theses" },
    { key: "presentations", label: "Presentations" },
    { key: "proceedings", label: "Proceedings" },
    { key: "technicalReports", label: "Technical Reports" }
];

export const allTags = [
    { key: "allTags", label: "All tags" },
    { key: "threeDMicroPhotonicStructures", label: "3D micro-photonic structures" },
    { key: "threeDPhotonicCrystal", label: "3D photonic crystal" },
    { key: "threeDPrintedCircuits", label: "3D printed circuits" },
    { key: "threeDPrinting", label: "3D printing" },
    { key: "additivesManufacturing", label: "additives manufacturing" },
    { key: "algorithmDevelopment", label: "algorithm development" },
    { key: "allDielectric", label: "all-dielectric" },
    { key: "allDielectricAntenna", label: "all-dielectric antenna" },
    { key: "allDielectricPhotonicCrystal", label: "all-dielectric photonic crystal" },
    { key: "allDielectricStructures", label: "all-dielectric structures" },
    { key: "anisotropicFiniteDifferenceTimeDomain", label: "anisotropic finite-difference time-domain" },
    { key: "anisotropy", label: "anisotropy" },
    { key: "applicationSoftware", label: "application software" },
    { key: "applied", label: "Applied" },
    { key: "arbitraryConformalArray", label: "arbitrary conformal array" },
    { key: "automation", label: "automation" },
    { key: "beamShaping", label: "beam shaping" },
    { key: "birefringent", label: "birefringent" },
    { key: "birefringentGrating", label: "birefringent grating" },
    { key: "cepstralFiltering", label: "cepstral filtering" },
    { key: "circuitDesign", label: "circuit design" },
    { key: "closedRingResonators", label: "closed ring resonators" },
    { key: "compositeMaterials", label: "composite materials" },
    { key: "computerEngineering", label: "computer engineering" },
    { key: "conformalFrequencySelectiveSurface", label: "conformal frequency selective surface" },
    { key: "conformalMapping", label: "conformal mapping" },
    { key: "copper", label: "copper" },
    { key: "culturalAlgorithm", label: "cultural algorithm" },
    { key: "curvedSurface", label: "curved surface" },
    { key: "depositionProcesses", label: "deposition processes" },
    { key: "dielectricDevices", label: "dielectric devices" },
    { key: "dielectricFilter", label: "dielectric filter" },
    { key: "dielectricStack", label: "dielectric stack" },
    { key: "dielectrics", label: "dielectrics" },
    { key: "diffractionGratings", label: "diffraction gratings" },
    { key: "diffractiveOptics", label: "diffractive optics" },
    { key: "effectiveRefractiveIndex", label: "Effective refractive index" },
    { key: "electromagneticAnalysis", label: "electromagnetic analysis" },
    { key: "electromagneticCloaking", label: "electromagnetic cloaking" },
    { key: "electromagneticDevices", label: "electromagnetic devices" },
    { key: "electromagneticModeling", label: "electromagnetic modeling" },
    { key: "electromagneticTesting", label: "electromagnetic testing" },
    { key: "electronBeamMelting", label: "electron beam melting" },
    { key: "electronicsPackaging", label: "electronics packaging" },
    { key: "etching", label: "etching" },
    { key: "extremeEnvironments", label: "extreme environments" },
    { key: "faceCenteredCubicPhotonicCrystal", label: "face-centered-cubic photonic crystal" },
    { key: "fdm", label: "FDM" },
    { key: "fiberBraggGrating", label: "fiber-bragg grating" },
    { key: "figureOfMerit", label: "figure of merit" },
    { key: "finiteElementAnalysis", label: "finite element analysis" },
    { key: "finiteDifferenceFrequencyDomain", label: "finite-difference frequency-domain (FDFD)" },
    { key: "forwardScattering", label: "forward scattering" },
    { key: "frequencyModulation", label: "frequency modulation" },
    { key: "frequencySelectiveSurface", label: "frequency selective surface (FSS)" },
    { key: "functionallyGraded", label: "fuctionally graded" },
    { key: "fusedDepositionModeling", label: "fused deposition modeling" },
    { key: "geneticAlgorithm", label: "genetic algorithm" },
    { key: "gmr", label: "GMR" },
    { key: "gmrf", label: "GMRF" },
    { key: "gratings", label: "gratings" },
    { key: "guidedMode", label: "guided mode" },
    { key: "guidedModeResonance", label: "guided mode resonance (GMR)" },
    { key: "hexagonal", label: "hexagonal" },
    { key: "highPowerMicrowave", label: "high power microwave" },
    { key: "highFrequencyFilters", label: "high-frequency filters" },
    { key: "holographicLithography", label: "holographic lithography" },
    { key: "homogeneousNarrowbandSpectralFilter", label: "homogeneous narrowband spectral filter" },
    { key: "hybrid3DPrinting", label: "hybrid 3D printing" },
    { key: "imageFiltering", label: "image filtering" },
    { key: "inverseDesign", label: "inverse design" },
    { key: "iron", label: "iron" },
    { key: "iterativeMethods", label: "iterative methods" },
    { key: "kSpaceDesign", label: "k-space design" },
    { key: "largeScale3DPrinting", label: "large-scale 3D  printing" }
    // Continue for the remaining options as needed.
];

export const allAuthors = [
    { key: "allAuthors", label: "All authors" },
    { key: "aChavezL", label: "A., Chavez L." },
    { key: "anSangsup", label: "An, Sangsup" },
    { key: "avilaJoseAntonio", label: "Avila, Jose Antonio" },
    { key: "avilaJose", label: "Avila, Jose" },
    { key: "bartonJayH", label: "Barton, Jay H" },
    { key: "bartonJayHouston", label: "Barton, Jay Houston" },
    { key: "bartonJH", label: "Barton, JH" },
    { key: "batistaDaniel", label: "Batista, Daniel" },
    { key: "benitezTenoch", label: "Benitez, Tenoch" },
    { key: "berryEA", label: "Berry, EA" },
    { key: "berryEricA", label: "Berry, Eric A" },
    { key: "berryEricA_3", label: "Berry, Eric A." },
    { key: "bilalOR", label: "Bilal, O. R." },
    { key: "boremanGlennD", label: "Boreman, Glenn D" },
    { key: "bresnahanPeter", label: "Bresnahan, Peter" },
    { key: "brownJeremiahD", label: "Brown, Jeremiah D" },
    { key: "brownStephenB", label: "Brown, Stephen B" },
    { key: "buhlK", label: "Buhl, K" },
    { key: "buhlKaia", label: "Buhl, Kaia" },
    { key: "bustamanteEdgar", label: "Bustamante, Edgar" },
    { key: "cadenaMonicaA", label: "Cadena, Monica A" },
    { key: "carranzaGilbert", label: "Carranza, Gilbert" },
    { key: "carranzaGilbertT", label: "Carranza, Gilbert T" },
    { key: "carranzaGilbertT_3", label: "Carranza, Gilbert T." },
    { key: "chavezLA", label: "Chavez, L. A." },
    { key: "chavezLuisA", label: "Chavez, Luis A" },
    { key: "chenYunSheng", label: "Chen, Yun-Sheng" },
    { key: "chilesJeff", label: "Chiles, Jeff" },
    { key: "chilesJeffrey", label: "Chiles, Jeffrey" },
    { key: "choudhuriAhsan", label: "Choudhuri, Ahsan" },
    { key: "choudhuriAhsanR", label: "Choudhuri, Ahsan R" },
    { key: "churchKenneth", label: "Church, Kenneth" },
    { key: "churchKennethH", label: "Church, Kenneth H" },
    { key: "churchKennethH_3", label: "Church, Kenneth H." },
    { key: "cockerhamAlexanderR", label: "Cockerham, Alexander R" },
    { key: "cockerhamAlexanderR_3", label: "Cockerham, Alexander R." },
    { key: "cogginJohn", label: "Coggin, John" },
    { key: "correaJesus", label: "Correa, Jesus" },
    { key: "curtisChristopher", label: "Curtis, Christopher" },
    { key: "delfinD", label: "D., Delfin" },
    { key: "dArchangelJeffrey", label: "D’Archangel, Jeffrey" },
    { key: "darshniPrya", label: "Darshni, Prya" },
    { key: "davisWilliamA", label: "Davis, William A" },
    { key: "davisWilliams", label: "Davis, Williams" },
    { key: "davoodFathi", label: "Davood Fathi," },
    { key: "defembaughPaul", label: "Defembaugh, Paul" },
    { key: "deffenbaughPaul", label: "Deffenbaugh, Paul" },
    { key: "deffenbaughPaulI", label: "Deffenbaugh, Paul I" },
    { key: "deffenbaughPaulIssac", label: "Deffenbaugh, Paul Issac" },
    { key: "delfinD_3", label: "Delfin, D." },
    { key: "delfinDiego", label: "Delfin, Diego" },
    { key: "delfinLuis", label: "Delfin, Luis" },
    { key: "delphinD", label: "Delphin, D." },
    { key: "digaumJenefirL", label: "Digaum, Jenefir L" },
    { key: "digaumJennefir", label: "Digaum, Jennefir" },
    { key: "digaumJennefirL", label: "Digaum, Jennefir L" },
    { key: "digaumJennefirL_3", label: "Digaum, Jennefir L." },
    { key: "dominguezUbaldoRobles", label: "Dominguez, Ubaldo Robles" },
    { key: "dumasJeremie", label: "Dumas, Jeremie" },
    { key: "egJohnson", label: "E.G., Johnson" },
    { key: "enriquezJoseLuis", label: "Enriquez, Jose Luis" },
    { key: "enriquezRE", label: "Enriquez, R. E." },
    { key: "enriquezR", label: "Enriquez, R." },
    { key: "espalinDavid", label: "Espalin, David" },
    { key: "fathiDavood", label: "Fathi, Davood" },
    { key: "fathiDavood_3", label: "Fathi, Davood" },
    { key: "fathpourSasan", label: "Fathpour, Sasan" },
    { key: "fiddyMA", label: "Fiddy, M. A." },
    { key: "fiddyMichaelA", label: "Fiddy, Michael A" },
    { key: "flynnTom", label: "Flynn, Tom" },
    { key: "frepponDanielJ", label: "Freppon, Daniel J" },
    { key: "freymannGeorg", label: "Freymann, Georg" },
    { key: "freymannGeorgVon", label: "Freymann, Georg Von" },
    { key: "gamlenCarolA", label: "Gamlen, Carol A" },
    { key: "gamlenCarol", label: "Gamlen, Carol" },
    { key: "garciaCesarR", label: "Garcia, Cesar R" },
    { key: "garciaCesarR_3", label: "Garcia, Cesar R." },
    { key: "garciaCesarRoman", label: "Garcia, Cesar Roman" },
    { key: "garciaCR", label: "Garcia, CR" },
    { key: "gatesMarvin", label: "Gates, Marvin" },
    { key: "gaytanSaraM", label: "Gaytan, Sara M" },
    { key: "gonzalezVirgilio", label: "Gonzalez, Virgilio" },
    { key: "grabillChristopherN", label: "Grabill, Christopher N" },
    { key: "grabillChristopherN_3", label: "Grabill, Christopher N." },
    { key: "grayDT", label: "Gray, DT" },
    { key: "guitierrezJesusJ", label: "Guitierrez, Jesus J." },
    { key: "gulibAsadUllahHil", label: "Gulib, Asad Ullah Hil" },
    { key: "guoQ", label: "Guo, Q." }
];

export const publications = [
    {
        authors: ["Tsang", "Harvey Hing-Cheong"],
        title: "Digital processes and characterization for fabricating 3D RF devices",
        publicationTypes: ["PhD Thesis"],
        description: ", (989774427  by Harvey Hing-Cheong Tsang.  illustrations (mostly color) ; 4 3/4 inches.  Vita.  Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP  CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.  University of Texas at El Paso. Doctoral dissertation.)",
        publishedYear: 2016,
        links: ["https://digitalcommons.utep.edu/open_etd/657"],
        bibTex: [
            "Numerical calculation of spatially variant anisotropic metamaterials",
            "Asad Ullah Hil Gulib",
            "https://digitalcommons.utep.edu/open_etd/657",
            "2016",
            "2016-12-01",
            "2016-12-01",
            "1 computer disc (x, 42 pages)",
            "983795860",
            "by Asad Ullah Hil Gulib.",
            "illustrations (mostly color) ; 4 3/4 inches.",
            "Vita.",
            "Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP",
            "CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.",
            "University of Texas at El Paso. Master's thesis.",
            "3D printing, additives manufacturing, anisotropy, composite materials, electromagnetic testing, manufacturing processes, metamaterials",
            "published",
            "mastersthesis"
        ],
        tags: ["3D Printing", "additives manufacturing"],
        abstract:""

    },
    {
        authors: ["Tsang", "Harvey Hing-Cheong"],
        title: "Digital processes and characterization for fabricating 3D RF devices",
        publicationTypes: ["PhD Thesis"],
        description: ", (989774427  by Harvey Hing-Cheong Tsang.  illustrations (mostly color) ; 4 3/4 inches.  Vita.  Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP  CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.  University of Texas at El Paso. Doctoral dissertation.)",
        publishedYear: 2016,
        links: ["https://digitalcommons.utep.edu/open_etd/657"],
        bibTex: [
            "Numerical calculation of spatially variant anisotropic metamaterials",
            "Asad Ullah Hil Gulib",
            "https://digitalcommons.utep.edu/open_etd/657",
            "2016",
            "2016-12-01",
            "2016-12-01",
            "1 computer disc (x, 42 pages)",
            "983795860",
            "by Asad Ullah Hil Gulib.",
            "illustrations (mostly color) ; 4 3/4 inches.",
            "Vita.",
            "Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP",
            "CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.",
            "University of Texas at El Paso. Master's thesis.",
            "3D printing, additives manufacturing, anisotropy, composite materials, electromagnetic testing, manufacturing processes, metamaterials",
            "published",
            "mastersthesis"
        ],
        tags: ["3D Printing", "additives manufacturing"],
        abstract:""

    },
    {
        authors: ["Tsang", "Harvey Hing-Cheong"],
        title: "Digital processes and characterization for fabricating 3D RF devices",
        publicationTypes: ["PhD Thesis"],
        description: ", (989774427  by Harvey Hing-Cheong Tsang.  illustrations (mostly color) ; 4 3/4 inches.  Vita.  Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP  CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.  University of Texas at El Paso. Doctoral dissertation.)",
        publishedYear: 2014,
        links: ["https://digitalcommons.utep.edu/open_etd/657"],
        bibTex: [
            "Numerical calculation of spatially variant anisotropic metamaterials",
            "Asad Ullah Hil Gulib",
            "https://digitalcommons.utep.edu/open_etd/657",
            "2016",
            "2016-12-01",
            "2016-12-01",
            "1 computer disc (x, 42 pages)",
            "983795860",
            "by Asad Ullah Hil Gulib.",
            "illustrations (mostly color) ; 4 3/4 inches.",
            "Vita.",
            "Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP",
            "CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.",
            "University of Texas at El Paso. Master's thesis.",
            "3D printing, additives manufacturing, anisotropy, composite materials, electromagnetic testing, manufacturing processes, metamaterials",
            "published",
            "mastersthesis"
        ],
        tags: ["3D Printing", "additives manufacturing"],
        abstract:""

    },
    {
        authors: ["Tsang", "Harvey Hing-Cheong"],
        title: "Digital processes and characterization for fabricating 3D RF devices",
        publicationTypes: ["PhD Thesis"],
        description: ", (989774427  by Harvey Hing-Cheong Tsang.  illustrations (mostly color) ; 4 3/4 inches.  Vita.  Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP  CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.  University of Texas at El Paso. Doctoral dissertation.)",
        publishedYear: 2012,
        links: ["https://digitalcommons.utep.edu/open_etd/657"],
        bibTex: [
            "Numerical calculation of spatially variant anisotropic metamaterials",
            "Asad Ullah Hil Gulib",
            "https://digitalcommons.utep.edu/open_etd/657",
            "2016",
            "2016-12-01",
            "2016-12-01",
            "1 computer disc (x, 42 pages)",
            "983795860",
            "by Asad Ullah Hil Gulib.",
            "illustrations (mostly color) ; 4 3/4 inches.",
            "Vita.",
            "Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP",
            "CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.",
            "University of Texas at El Paso. Master's thesis.",
            "3D printing, additives manufacturing, anisotropy, composite materials, electromagnetic testing, manufacturing processes, metamaterials",
            "published",
            "mastersthesis"
        ],
        tags: ["3D Printing", "additives manufacturing"],
        abstract:""

    },
    {
        authors: ["Tsang", "Harvey Hing-Cheong"],
        title: "Digital processes and characterization for fabricating 3D RF devices",
        publicationTypes: ["PhD Thesis"],
        description: ", (989774427  by Harvey Hing-Cheong Tsang.  illustrations (mostly color) ; 4 3/4 inches.  Vita.  Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP  CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.  University of Texas at El Paso. Doctoral dissertation.)",
        publishedYear: 2016,
        links: ["https://digitalcommons.utep.edu/open_etd/657"],
        bibTex: [
            "Numerical calculation of spatially variant anisotropic metamaterials",
            "Asad Ullah Hil Gulib",
            "https://digitalcommons.utep.edu/open_etd/657",
            "2016",
            "2016-12-01",
            "2016-12-01",
            "1 computer disc (x, 42 pages)",
            "983795860",
            "by Asad Ullah Hil Gulib.",
            "illustrations (mostly color) ; 4 3/4 inches.",
            "Vita.",
            "Includes bibliographical references. Also available online via ProQuest Dissertations and Theses @ UTEP",
            "CD-ROM requires Adobe Acrobat Reader and CD-ROM drive.",
            "University of Texas at El Paso. Master's thesis.",
            "3D printing, additives manufacturing, anisotropy, composite materials, electromagnetic testing, manufacturing processes, metamaterials",
            "published",
            "mastersthesis"
        ],
        tags: ["3D Printing", "additives manufacturing"],
        abstract:""

    },
];